### ISSUE TITLE
vite] http proxy error at /api/sentiment/pcrAnalyzer/index:

### ISSUE THREAD

**Issue by ramjak2** [devfinwiz/Fin-Maestro-Web#56]
Hi

Below error is shown when VITE server started. Can you pls let me know how to fix the proxy eror.

  VITE v3.2.7  ready in 390 ms

  ➜  Local:   http://localhost:80/
  ➜  Network: http://192.168.200.224:80/
1:05:54 PM [vite] http proxy error at /api/sentiment/pcrAnalyzer/index:
Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
1:05:54 PM [vite] http proxy error at /api/valuation/index:
Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
1:06:45 PM [vite] http proxy error at /api/tickers:
Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
1:06:47 PM [vite] http proxy error at /api/sentiment/pcrAnalyzer/index:
Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
1:06:47 PM [vite] http proxy error at /api/valuation/index:
Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
1:08:37 PM [vite] http proxy error at /api/sentiment/pcrAnalyzer/index:
Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
1:08:37 PM [vite] http proxy error at /api/valuation/index:
Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)

**Comment by devfinwiz** [comment]
Hi @ramjak2,
This repository is no longer being maintained due to absence of any active maintainers/contributors. There may be a huge disconnect between the actual frontend(Vue on docker branch) and backend causing this failure. I am unable to do it myself due to my commitments towards work place and new ongoing open source project - https://github.com/devfinwiz/Fin-Maestro-Kin. 

Alternative for you:

1. Switch to master branch.
2. Try using https://github.com/devfinwiz/Fin-Maestro-Web/blob/master/CommonFEGradio/driver.py. This is an alternate frontend to execute some key modules of the project. 
3. Make sure to have all the dependencies resolved in your environment. 

The new open source project mentioned above will ensure creation of an independent API that will function 24/7 with ease of quick deployment and documentation. It will comprise of existing Fin-Maestro-Web modules and many new ones ensuring availability of processed financial data to extract useful insights.
